------------------------------------------------------------------------
-- 0) 세션 설정 (선택)
------------------------------------------------------------------------
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

------------------------------------------------------------------------
-- 1) 유저
------------------------------------------------------------------------
CREATE TABLE "user" (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(50)   NOT NULL,
    email        VARCHAR2(100)  NOT NULL UNIQUE,
    password     VARCHAR2(255)  NOT NULL,
    nickname     VARCHAR2(50),
    created_at   DATE DEFAULT SYSDATE NOT NULL
);

------------------------------------------------------------------------
-- 2) 카테고리
------------------------------------------------------------------------
CREATE TABLE category (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(50) NOT NULL UNIQUE
);

------------------------------------------------------------------------
-- 3) 주소
------------------------------------------------------------------------
CREATE TABLE address (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address         VARCHAR2(120),
    detail_address  VARCHAR2(120),            -- 상세주소
    user_id         NUMBER NOT NULL,          -- 사용자
    default_address CHAR(1) DEFAULT 'N' CHECK (default_address IN ('Y','N'))
);

ALTER TABLE address
    ADD CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES "user"(id);

------------------------------------------------------------------------
-- 4) 물품
------------------------------------------------------------------------
CREATE TABLE item (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR2(100) NOT NULL,
    text          CLOB,
    start_price   NUMBER NOT NULL CHECK (start_price >= 0),
    current_price NUMBER NOT NULL CHECK (current_price >= 0),
    end_time      DATE NOT NULL,
    status        VARCHAR2(10) NOT NULL CHECK (status IN ('OPEN','CLOSED','FAILED')),
    created_at    DATE DEFAULT SYSDATE NOT NULL,
    seller_id     NUMBER NOT NULL,
    category_id   NUMBER NOT NULL
);

ALTER TABLE item
    ADD CONSTRAINT fk_item_seller FOREIGN KEY (seller_id) REFERENCES "user"(id);
ALTER TABLE item
    ADD CONSTRAINT fk_item_category FOREIGN KEY (category_id) REFERENCES category(id);

------------------------------------------------------------------------
-- 5) 물품 이미지
------------------------------------------------------------------------
CREATE TABLE item_image (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url  VARCHAR2(400) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    item_id    NUMBER NOT NULL
);

ALTER TABLE item_image
    ADD CONSTRAINT fk_item_image_item FOREIGN KEY (item_id) REFERENCES item(id);

------------------------------------------------------------------------
-- 6) 입찰 내역
------------------------------------------------------------------------
CREATE TABLE bid (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_price  NUMBER NOT NULL CHECK (bid_price > 0),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    bid_item_id  NUMBER NOT NULL,
    bid_user_id  NUMBER NOT NULL
);

ALTER TABLE bid
    ADD CONSTRAINT fk_bid_item FOREIGN KEY (bid_item_id) REFERENCES item(id);
ALTER TABLE bid
    ADD CONSTRAINT fk_bid_user FOREIGN KEY (bid_user_id) REFERENCES "user"(id);

------------------------------------------------------------------------
-- 7) 거래 결과
------------------------------------------------------------------------
CREATE TABLE transaction (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price           NUMBER NOT NULL,
    created_at      DATE DEFAULT SYSDATE NOT NULL,
    user_id         NUMBER NOT NULL,   -- 거래자(구매자)
    item_id         NUMBER NOT NULL    -- 거래된 아이템
);

ALTER TABLE transaction
    ADD CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES "user"(id);
ALTER TABLE transaction
    ADD CONSTRAINT fk_transaction_item FOREIGN KEY (item_id) REFERENCES item(id);

------------------------------------------------------------------------
-- 8) 찜
------------------------------------------------------------------------
CREATE TABLE favorite (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    user_id    NUMBER NOT NULL,
    item_id    NUMBER NOT NULL
);

ALTER TABLE favorite
    ADD CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES "user"(id);
ALTER TABLE favorite
    ADD CONSTRAINT fk_favorite_item FOREIGN KEY (item_id) REFERENCES item(id);

ALTER TABLE favorite
    ADD CONSTRAINT uq_favorite UNIQUE (user_id, item_id);

------------------------------------------------------------------------
-- 9) 리뷰
------------------------------------------------------------------------
CREATE TABLE review (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating     NUMBER(2,1) NOT NULL CHECK (rating BETWEEN 0 AND 5),
    comment    CLOB,
    user_id1   NUMBER NOT NULL, -- 리뷰 작성자
    user_id2   NUMBER NOT NULL  -- 리뷰 대상자
);

ALTER TABLE review
    ADD CONSTRAINT fk_review_user1 FOREIGN KEY (user_id1) REFERENCES "user"(id);
ALTER TABLE review
    ADD CONSTRAINT fk_review_user2 FOREIGN KEY (user_id2) REFERENCES "user"(id);

------------------------------------------------------------------------
-- 10) 태그 종류
------------------------------------------------------------------------
CREATE TABLE review_tag (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR2(50) NOT NULL
);

------------------------------------------------------------------------
-- 11) 리뷰-태그 매핑 (N:M)
------------------------------------------------------------------------
CREATE TABLE tag (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id  NUMBER NOT NULL,
    tag_id     NUMBER NOT NULL
);

ALTER TABLE tag
    ADD CONSTRAINT fk_tag_review FOREIGN KEY (review_id) REFERENCES review(id);
ALTER TABLE tag
    ADD CONSTRAINT fk_tag_reviewtag FOREIGN KEY (tag_id) REFERENCES review_tag(id);

ALTER TABLE tag
    ADD CONSTRAINT uq_tag UNIQUE (review_id, tag_id);

------------------------------------------------------------------------
-- 12) 1:1 채팅방
------------------------------------------------------------------------
CREATE TABLE dm_chat_room (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    user_id1   NUMBER NOT NULL,
    user_id2   NUMBER NOT NULL
);

ALTER TABLE dm_chat_room
    ADD CONSTRAINT fk_dm_user1 FOREIGN KEY (user_id1) REFERENCES "user"(id);
ALTER TABLE dm_chat_room
    ADD CONSTRAINT fk_dm_user2 FOREIGN KEY (user_id2) REFERENCES "user"(id);

------------------------------------------------------------------------
-- 13) 1:1 채팅 메시지
------------------------------------------------------------------------
CREATE TABLE dm_chat_message (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    NUMBER NOT NULL,
    user_id    NUMBER NOT NULL,
    msg        CLOB NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE dm_chat_message
    ADD CONSTRAINT fk_dm_msg_room FOREIGN KEY (room_id) REFERENCES dm_chat_room(id);
ALTER TABLE dm_chat_message
    ADD CONSTRAINT fk_dm_msg_user FOREIGN KEY (user_id) REFERENCES "user"(id);

------------------------------------------------------------------------
-- 14) 경매 채팅방
------------------------------------------------------------------------
CREATE TABLE auction_chat_room (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE auction_chat_room
    ADD CONSTRAINT fk_acr_item FOREIGN KEY (item_id) REFERENCES item(id);

------------------------------------------------------------------------
-- 15) 경매 채팅 메시지
------------------------------------------------------------------------
CREATE TABLE auction_chat_message (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msg        CLOB NOT NULL,
    room_id    NUMBER NOT NULL,
    user_id    NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE auction_chat_message
    ADD CONSTRAINT fk_acm_room FOREIGN KEY (room_id) REFERENCES auction_chat_room(id);
ALTER TABLE auction_chat_message
    ADD CONSTRAINT fk_acm_user FOREIGN KEY (user_id) REFERENCES "user"(id);

------------------------------------------------------------------------
-- 16) 알림
------------------------------------------------------------------------
CREATE TABLE notification (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    CLOB NOT NULL,
    url        VARCHAR2(400),
    is_read    CHAR(1) DEFAULT 'N' CHECK (is_read IN ('Y','N')),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    user_id    NUMBER NOT NULL,
    item_id    NUMBER NOT NULL
);

ALTER TABLE notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES "user"(id);
ALTER TABLE notification 
    ADD CONSTRAINT fk_notification_item FOREIGN KEY (item_id) REFERENCES item(id);
